name: cicd
on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check PEP8 compliance
        run: |
          black --check --verbose .
      - name: Lint with mypy
        run: |
          mypy .
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.4.1'
          hadoop-version: '3'
      - name: Test main py
        run: python3 test.py
    
  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dskirill/otusfrd:latest
      
     
